export interface Question {
  id: string;
  category: string;
  question: string;
  options: { A: string; B: string; C: string; D: string };
  correct: "A" | "B" | "C" | "D";
  explanation: string;
  points: number;
  timeLimit: number; // seconds
}

export const QUESTIONS: Question[] = [
  // ── Cardano Fundamentals ──────────────────────────────────────────────────
  {
    id: "q01",
    category: "Fundamentals",
    question: "What consensus protocol does Cardano use?",
    options: {
      A: "Proof of Work (Nakamoto)",
      B: "Delegated Proof of Stake (DPoS)",
      C: "Ouroboros Proof of Stake",
      D: "Proof of Authority (PoA)",
    },
    correct: "C",
    explanation: "Cardano uses Ouroboros — the first provably secure PoS protocol, peer-reviewed and published in academic conferences.",
    points: 100,
    timeLimit: 30,
  },
  {
    id: "q02",
    category: "Fundamentals",
    question: "Ada Lovelace, after whom ADA is named, is considered to be what?",
    options: {
      A: "The first blockchain developer",
      B: "The world's first computer programmer",
      C: "The founder of the Cardano Foundation",
      D: "The inventor of cryptography",
    },
    correct: "B",
    explanation: "Ada Lovelace (1815–1852) wrote the first algorithm intended for a machine — she is widely regarded as the world's first computer programmer.",
    points: 100,
    timeLimit: 25,
  },
  {
    id: "q03",
    category: "Fundamentals",
    question: "What is the maximum supply of ADA?",
    options: { A: "21 million", B: "1 billion", C: "45 billion", D: "100 trillion" },
    correct: "C",
    explanation: "ADA has a hard cap of 45 billion tokens. Currently around 36 billion are in circulation.",
    points: 100,
    timeLimit: 25,
  },
  {
    id: "q04",
    category: "Fundamentals",
    question: "What does eUTXO stand for in Cardano's accounting model?",
    options: {
      A: "Extended Unspent Transaction Output",
      B: "Encrypted Universal Transaction Output",
      C: "Enterprise UTXO for business use",
      D: "External UTXO cross-chain model",
    },
    correct: "A",
    explanation: "eUTXO (Extended UTXO) extends Bitcoin's UTXO model to support smart contract logic by attaching datum and redeemer to outputs.",
    points: 150,
    timeLimit: 35,
  },
  {
    id: "q05",
    category: "Fundamentals",
    question: "Where is the Cardano Foundation headquartered?",
    options: { A: "San Francisco, USA", B: "London, UK", C: "Zug, Switzerland", D: "Singapore" },
    correct: "C",
    explanation: "The Cardano Foundation is based in Zug, Switzerland — known as 'Crypto Valley' for its blockchain-friendly regulations.",
    points: 100,
    timeLimit: 25,
  },

  // ── Technology ──────────────────────────────────────────────────────────
  {
    id: "q06",
    category: "Technology",
    question: "What programming language is Plutus (Cardano's smart contract platform) based on?",
    options: { A: "JavaScript", B: "Haskell", C: "Rust", D: "Python" },
    correct: "B",
    explanation: "Plutus is built on Haskell — a purely functional language known for mathematical correctness and strong type safety.",
    points: 150,
    timeLimit: 30,
  },
  {
    id: "q07",
    category: "Technology",
    question: "What is Aiken on Cardano?",
    options: {
      A: "A Cardano hardware wallet",
      B: "A cross-chain bridge protocol",
      C: "A modern smart contract language for Cardano",
      D: "A Cardano DEX",
    },
    correct: "C",
    explanation: "Aiken is a modern, developer-friendly smart contract language for Cardano — simpler than Plutus with a Rust-like syntax.",
    points: 150,
    timeLimit: 30,
  },
  {
    id: "q08",
    category: "Technology",
    question: "What is Cardano's Layer-2 scaling solution called?",
    options: { A: "Lightning Network", B: "Polygon Edge", C: "Hydra", D: "Rollux" },
    correct: "C",
    explanation: "Hydra is Cardano's Layer-2 scaling protocol. Each Hydra Head can process thousands of TPS off-chain while settling on Cardano mainnet.",
    points: 150,
    timeLimit: 30,
  },
  {
    id: "q09",
    category: "Technology",
    question: "What Cardano hard fork introduced native tokens (multi-asset support)?",
    options: { A: "Byron", B: "Shelley", C: "Mary", D: "Alonzo" },
    correct: "C",
    explanation: "The Mary hard fork (March 2021) introduced native multi-asset support, allowing anyone to mint tokens on Cardano without smart contracts.",
    points: 150,
    timeLimit: 35,
  },
  {
    id: "q10",
    category: "Technology",
    question: "What is Marlowe on Cardano?",
    options: {
      A: "A block explorer for Cardano",
      B: "A domain-specific language for financial smart contracts",
      C: "A Cardano NFT marketplace",
      D: "A Cardano wallet browser extension",
    },
    correct: "B",
    explanation: "Marlowe is Cardano's DSL designed for financial agreements. It lets non-developers create DeFi contracts using visual tools.",
    points: 150,
    timeLimit: 35,
  },

  // ── Governance ──────────────────────────────────────────────────────────
  {
    id: "q11",
    category: "Governance",
    question: "What is CIP-1694?",
    options: {
      A: "A standard for NFT metadata on Cardano",
      B: "Cardano's on-chain governance framework proposal",
      C: "A cross-chain bridge specification",
      D: "The Cardano staking rewards formula",
    },
    correct: "B",
    explanation: "CIP-1694 defines Cardano's on-chain governance system — the foundation for the Voltaire era with DReps, SPOs, and the Constitutional Committee.",
    points: 200,
    timeLimit: 35,
  },
  {
    id: "q12",
    category: "Governance",
    question: "What does DRep stand for in Cardano governance?",
    options: {
      A: "Digital Resource Exchange Protocol",
      B: "Delegated Representative",
      C: "Decentralized Registry Entry Protocol",
      D: "Direct Reward Epoch Parameter",
    },
    correct: "B",
    explanation: "DReps (Delegated Representatives) are governance delegates in Cardano's Voltaire era. ADA holders can delegate voting power to them.",
    points: 200,
    timeLimit: 35,
  },
  {
    id: "q13",
    category: "Governance",
    question: "What is Intersect MBO?",
    options: {
      A: "A Cardano DEX aggregator",
      B: "A member-based organization managing Cardano's governance and development",
      C: "A blockchain analytics platform",
      D: "A Cardano staking pool operator group",
    },
    correct: "B",
    explanation: "Intersect is a member-based organization founded in 2023 to steward Cardano's governance, manage the treasury, and coordinate development.",
    points: 200,
    timeLimit: 35,
  },
  {
    id: "q14",
    category: "Governance",
    question: "What is Project Catalyst on Cardano?",
    options: {
      A: "A Layer-2 scaling project",
      B: "Cardano's community-governed innovation fund",
      C: "A cross-chain token bridge",
      D: "A Cardano DEX protocol",
    },
    correct: "B",
    explanation: "Project Catalyst is Cardano's community fund — one of the world's largest decentralized innovation funds, with $1B+ in the treasury.",
    points: 150,
    timeLimit: 30,
  },
  {
    id: "q15",
    category: "Governance",
    question: "The Chang hard fork (2024) enabled which major feature on Cardano?",
    options: {
      A: "Smart contracts",
      B: "Native tokens",
      C: "On-chain governance (CIP-1694)",
      D: "Staking delegation",
    },
    correct: "C",
    explanation: "Chang (named after Philip Chang) introduced the first phase of Cardano's on-chain governance, activating DReps and governance actions.",
    points: 200,
    timeLimit: 35,
  },

  // ── Ecosystem ──────────────────────────────────────────────────────────
  {
    id: "q16",
    category: "Ecosystem",
    question: "Which Cardano project built a digital identity system for Ethiopian students?",
    options: { A: "Cardano Foundation", B: "Atala PRISM by IOHK", C: "EMURGO", D: "Minswap" },
    correct: "B",
    explanation: "IOHK's Atala PRISM partnered with Ethiopia's Ministry of Education to issue blockchain-verified IDs for 5 million students.",
    points: 150,
    timeLimit: 30,
  },
  {
    id: "q17",
    category: "Ecosystem",
    question: "What is the most widely used DEX (Decentralized Exchange) on Cardano?",
    options: { A: "Uniswap", B: "SundaeSwap", C: "Minswap", D: "Raydium" },
    correct: "C",
    explanation: "Minswap is Cardano's largest DEX by liquidity and volume, offering automated market making with the Cardano eUTXO model.",
    points: 150,
    timeLimit: 30,
  },
  {
    id: "q18",
    category: "Ecosystem",
    question: "What is the minimum ADA required in every UTXO on Cardano?",
    options: { A: "0 ADA (no minimum)", B: "1 ADA flat", C: "A protocol-set minimum (minUTxO)", D: "5 ADA" },
    correct: "C",
    explanation: "Every UTXO must carry a minimum ADA amount (minUTxO) calculated by the protocol based on the size of the datum and any native tokens.",
    points: 150,
    timeLimit: 35,
  },
  {
    id: "q19",
    category: "Ecosystem",
    question: "Which wallet is most popular for Cardano users?",
    options: { A: "MetaMask", B: "Phantom", C: "Eternl", D: "Trust Wallet" },
    correct: "C",
    explanation: "Eternl (formerly CCVault) is the most feature-rich Cardano wallet, supporting multi-account, hardware wallets, and governance features.",
    points: 100,
    timeLimit: 25,
  },
  {
    id: "q20",
    category: "Ecosystem",
    question: "What is Mithril on Cardano?",
    options: {
      A: "A Cardano NFT standard",
      B: "A lightweight client protocol using stake-based signature aggregation",
      C: "A DEX liquidity protocol",
      D: "A cross-chain messaging protocol",
    },
    correct: "B",
    explanation: "Mithril enables fast, trustless bootstrapping of Cardano nodes and wallets using stake-based multi-signatures — no full chain sync needed.",
    points: 200,
    timeLimit: 40,
  },

  // ── Africa & NBO ──────────────────────────────────────────────────────
  {
    id: "q21",
    category: "Africa & NBO",
    question: "Who co-founded IOHK (now IOG), the company building Cardano?",
    options: {
      A: "Vitalik Buterin and Gavin Wood",
      B: "Charles Hoskinson and Jeremy Wood",
      C: "Satoshi Nakamoto and Nick Szabo",
      D: "Anatoly Yakovenko and Raj Gokal",
    },
    correct: "B",
    explanation: "Charles Hoskinson (also Ethereum co-founder) and Jeremy Wood founded IOHK in 2015. It is now known as IOG (Input Output Global).",
    points: 150,
    timeLimit: 30,
  },
  {
    id: "q22",
    category: "Africa & NBO",
    question: "What is Cardano Hub Nairobi focused on?",
    options: {
      A: "Mining ADA tokens",
      B: "Educating and growing the Cardano community in East Africa",
      C: "Running Cardano stake pools only",
      D: "Building Cardano's Layer-2 solutions",
    },
    correct: "B",
    explanation: "Cardano Hub Nairobi builds and educates the local Cardano community, organizes meetups, and drives blockchain adoption across East Africa.",
    points: 100,
    timeLimit: 25,
  },
  {
    id: "q23",
    category: "Africa & NBO",
    question: "What is EMURGO's primary role in the Cardano ecosystem?",
    options: {
      A: "Academic research and protocol development",
      B: "Cardano Foundation governance",
      C: "Commercial adoption and enterprise blockchain solutions",
      D: "Running the Cardano treasury",
    },
    correct: "C",
    explanation: "EMURGO is Cardano's commercial arm, focused on enterprise blockchain solutions, startup incubation, and real-world ADA adoption.",
    points: 150,
    timeLimit: 30,
  },
  {
    id: "q24",
    category: "Africa & NBO",
    question: "What blockchain concept allows Cardano stake pool operators to participate in governance under CIP-1694?",
    options: {
      A: "SPOs vote via their existing stake pool keys",
      B: "SPOs cannot vote in governance",
      C: "SPOs must become DReps to vote",
      D: "Only ADA holders with 100,000 ADA can vote",
    },
    correct: "A",
    explanation: "Under CIP-1694, Stake Pool Operators (SPOs) are one of three governance bodies — they vote using their existing cold keys on certain governance actions.",
    points: 200,
    timeLimit: 40,
  },
  {
    id: "q25",
    category: "Recent News",
    question: "What major Cardano upgrade is expected in 2025 to further Voltaire governance?",
    options: {
      A: "Shelley 2.0",
      B: "Chang 2 / Plomin hard fork",
      C: "Basho scaling upgrade",
      D: "Byron refresh",
    },
    correct: "B",
    explanation: "The Plomin hard fork (Chang 2) completes the Voltaire era by enabling full community voting on treasury withdrawals and protocol parameters.",
    points: 200,
    timeLimit: 35,
  },
];
